run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

version: "2"

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true

linters:
  default: none
  enable:
    - godot
    - copyloopvar
    - gocyclo
    - misspell
    - rowserrcheck
    - staticcheck
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    # - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - loggercheck
    - makezero
    - mirror
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - sloglint
    - sqlclosecheck
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - paralleltest

  settings:
    govet:
      enable:
        - shadow
      disable:
        - fieldalignment
      settings:
        shadow:
          strict: true
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 120
    nolintlint:
      require-explanation: true
      require-specific: true
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - octalLiteral
        - hugeParam

  exclusions:
    generated: lax
    rules:
      - linters:
          - perfsprint
          - dupl
          - gochecknoglobals
          - gocognit
          - goconst
          - gocritic
          - gosec
          - govet
          - lll
          - revive
          - staticcheck
          - unparam
          - whitespace
          - gocyclo
          - cyclop
          - prealloc
        path: _test\.go
      - linters:
          - gochecknoglobals
        path: ^cmd/yandex-mcp/main\.go$
        text: "^(version|commit|date|builtBy) is a global variable"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default: error

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/n-r-w/yandex-mcp
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - loadtest$
      - profile$
      - bench$
