// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock_interfaces.go -package=tracker
//

// Package tracker is a generated GoMock package.
package tracker

import (
	context "context"
	reflect "reflect"

	domain "github.com/n-r-w/yandex-mcp/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockITrackerAdapter is a mock of ITrackerAdapter interface.
type MockITrackerAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockITrackerAdapterMockRecorder
	isgomock struct{}
}

// MockITrackerAdapterMockRecorder is the mock recorder for MockITrackerAdapter.
type MockITrackerAdapterMockRecorder struct {
	mock *MockITrackerAdapter
}

// NewMockITrackerAdapter creates a new mock instance.
func NewMockITrackerAdapter(ctrl *gomock.Controller) *MockITrackerAdapter {
	mock := &MockITrackerAdapter{ctrl: ctrl}
	mock.recorder = &MockITrackerAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITrackerAdapter) EXPECT() *MockITrackerAdapterMockRecorder {
	return m.recorder
}

// CountIssues mocks base method.
func (m *MockITrackerAdapter) CountIssues(ctx context.Context, opts domain.TrackerCountIssuesOpts) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountIssues", ctx, opts)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountIssues indicates an expected call of CountIssues.
func (mr *MockITrackerAdapterMockRecorder) CountIssues(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountIssues", reflect.TypeOf((*MockITrackerAdapter)(nil).CountIssues), ctx, opts)
}

// GetCurrentUser mocks base method.
func (m *MockITrackerAdapter) GetCurrentUser(ctx context.Context) (*domain.TrackerUserDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentUser", ctx)
	ret0, _ := ret[0].(*domain.TrackerUserDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentUser indicates an expected call of GetCurrentUser.
func (mr *MockITrackerAdapterMockRecorder) GetCurrentUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUser", reflect.TypeOf((*MockITrackerAdapter)(nil).GetCurrentUser), ctx)
}

// GetIssue mocks base method.
func (m *MockITrackerAdapter) GetIssue(ctx context.Context, issueID string, opts domain.TrackerGetIssueOpts) (*domain.TrackerIssue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssue", ctx, issueID, opts)
	ret0, _ := ret[0].(*domain.TrackerIssue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssue indicates an expected call of GetIssue.
func (mr *MockITrackerAdapterMockRecorder) GetIssue(ctx, issueID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssue", reflect.TypeOf((*MockITrackerAdapter)(nil).GetIssue), ctx, issueID, opts)
}

// GetIssueAttachment mocks base method.
func (m *MockITrackerAdapter) GetIssueAttachment(ctx context.Context, issueID, attachmentID, fileName string) (*domain.TrackerAttachmentContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssueAttachment", ctx, issueID, attachmentID, fileName)
	ret0, _ := ret[0].(*domain.TrackerAttachmentContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssueAttachment indicates an expected call of GetIssueAttachment.
func (mr *MockITrackerAdapterMockRecorder) GetIssueAttachment(ctx, issueID, attachmentID, fileName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssueAttachment", reflect.TypeOf((*MockITrackerAdapter)(nil).GetIssueAttachment), ctx, issueID, attachmentID, fileName)
}

// GetIssueAttachmentPreview mocks base method.
func (m *MockITrackerAdapter) GetIssueAttachmentPreview(ctx context.Context, issueID, attachmentID string) (*domain.TrackerAttachmentContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssueAttachmentPreview", ctx, issueID, attachmentID)
	ret0, _ := ret[0].(*domain.TrackerAttachmentContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssueAttachmentPreview indicates an expected call of GetIssueAttachmentPreview.
func (mr *MockITrackerAdapterMockRecorder) GetIssueAttachmentPreview(ctx, issueID, attachmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssueAttachmentPreview", reflect.TypeOf((*MockITrackerAdapter)(nil).GetIssueAttachmentPreview), ctx, issueID, attachmentID)
}

// GetIssueAttachmentPreviewStream mocks base method.
func (m *MockITrackerAdapter) GetIssueAttachmentPreviewStream(ctx context.Context, issueID, attachmentID string) (*domain.TrackerAttachmentStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssueAttachmentPreviewStream", ctx, issueID, attachmentID)
	ret0, _ := ret[0].(*domain.TrackerAttachmentStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssueAttachmentPreviewStream indicates an expected call of GetIssueAttachmentPreviewStream.
func (mr *MockITrackerAdapterMockRecorder) GetIssueAttachmentPreviewStream(ctx, issueID, attachmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssueAttachmentPreviewStream", reflect.TypeOf((*MockITrackerAdapter)(nil).GetIssueAttachmentPreviewStream), ctx, issueID, attachmentID)
}

// GetIssueAttachmentStream mocks base method.
func (m *MockITrackerAdapter) GetIssueAttachmentStream(ctx context.Context, issueID, attachmentID, fileName string) (*domain.TrackerAttachmentStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssueAttachmentStream", ctx, issueID, attachmentID, fileName)
	ret0, _ := ret[0].(*domain.TrackerAttachmentStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssueAttachmentStream indicates an expected call of GetIssueAttachmentStream.
func (mr *MockITrackerAdapterMockRecorder) GetIssueAttachmentStream(ctx, issueID, attachmentID, fileName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssueAttachmentStream", reflect.TypeOf((*MockITrackerAdapter)(nil).GetIssueAttachmentStream), ctx, issueID, attachmentID, fileName)
}

// GetIssueChangelog mocks base method.
func (m *MockITrackerAdapter) GetIssueChangelog(ctx context.Context, issueID string, opts domain.TrackerGetChangelogOpts) ([]domain.TrackerChangelogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssueChangelog", ctx, issueID, opts)
	ret0, _ := ret[0].([]domain.TrackerChangelogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssueChangelog indicates an expected call of GetIssueChangelog.
func (mr *MockITrackerAdapterMockRecorder) GetIssueChangelog(ctx, issueID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssueChangelog", reflect.TypeOf((*MockITrackerAdapter)(nil).GetIssueChangelog), ctx, issueID, opts)
}

// GetQueue mocks base method.
func (m *MockITrackerAdapter) GetQueue(ctx context.Context, queueID string, opts domain.TrackerGetQueueOpts) (*domain.TrackerQueueDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueue", ctx, queueID, opts)
	ret0, _ := ret[0].(*domain.TrackerQueueDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueue indicates an expected call of GetQueue.
func (mr *MockITrackerAdapterMockRecorder) GetQueue(ctx, queueID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueue", reflect.TypeOf((*MockITrackerAdapter)(nil).GetQueue), ctx, queueID, opts)
}

// GetUser mocks base method.
func (m *MockITrackerAdapter) GetUser(ctx context.Context, userID string) (*domain.TrackerUserDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(*domain.TrackerUserDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockITrackerAdapterMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockITrackerAdapter)(nil).GetUser), ctx, userID)
}

// ListBoardSprints mocks base method.
func (m *MockITrackerAdapter) ListBoardSprints(ctx context.Context, boardID string) ([]domain.TrackerSprint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBoardSprints", ctx, boardID)
	ret0, _ := ret[0].([]domain.TrackerSprint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBoardSprints indicates an expected call of ListBoardSprints.
func (mr *MockITrackerAdapterMockRecorder) ListBoardSprints(ctx, boardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBoardSprints", reflect.TypeOf((*MockITrackerAdapter)(nil).ListBoardSprints), ctx, boardID)
}

// ListBoards mocks base method.
func (m *MockITrackerAdapter) ListBoards(ctx context.Context) ([]domain.TrackerBoard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBoards", ctx)
	ret0, _ := ret[0].([]domain.TrackerBoard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBoards indicates an expected call of ListBoards.
func (mr *MockITrackerAdapterMockRecorder) ListBoards(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBoards", reflect.TypeOf((*MockITrackerAdapter)(nil).ListBoards), ctx)
}

// ListIssueAttachments mocks base method.
func (m *MockITrackerAdapter) ListIssueAttachments(ctx context.Context, issueID string) ([]domain.TrackerAttachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIssueAttachments", ctx, issueID)
	ret0, _ := ret[0].([]domain.TrackerAttachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIssueAttachments indicates an expected call of ListIssueAttachments.
func (mr *MockITrackerAdapterMockRecorder) ListIssueAttachments(ctx, issueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIssueAttachments", reflect.TypeOf((*MockITrackerAdapter)(nil).ListIssueAttachments), ctx, issueID)
}

// ListIssueComments mocks base method.
func (m *MockITrackerAdapter) ListIssueComments(ctx context.Context, issueID string, opts domain.TrackerListCommentsOpts) (*domain.TrackerCommentsPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIssueComments", ctx, issueID, opts)
	ret0, _ := ret[0].(*domain.TrackerCommentsPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIssueComments indicates an expected call of ListIssueComments.
func (mr *MockITrackerAdapterMockRecorder) ListIssueComments(ctx, issueID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIssueComments", reflect.TypeOf((*MockITrackerAdapter)(nil).ListIssueComments), ctx, issueID, opts)
}

// ListIssueLinks mocks base method.
func (m *MockITrackerAdapter) ListIssueLinks(ctx context.Context, issueID string) ([]domain.TrackerLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIssueLinks", ctx, issueID)
	ret0, _ := ret[0].([]domain.TrackerLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIssueLinks indicates an expected call of ListIssueLinks.
func (mr *MockITrackerAdapterMockRecorder) ListIssueLinks(ctx, issueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIssueLinks", reflect.TypeOf((*MockITrackerAdapter)(nil).ListIssueLinks), ctx, issueID)
}

// ListIssueTransitions mocks base method.
func (m *MockITrackerAdapter) ListIssueTransitions(ctx context.Context, issueID string) ([]domain.TrackerTransition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIssueTransitions", ctx, issueID)
	ret0, _ := ret[0].([]domain.TrackerTransition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIssueTransitions indicates an expected call of ListIssueTransitions.
func (mr *MockITrackerAdapterMockRecorder) ListIssueTransitions(ctx, issueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIssueTransitions", reflect.TypeOf((*MockITrackerAdapter)(nil).ListIssueTransitions), ctx, issueID)
}

// ListProjectComments mocks base method.
func (m *MockITrackerAdapter) ListProjectComments(ctx context.Context, projectID string, opts domain.TrackerListProjectCommentsOpts) ([]domain.TrackerProjectComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectComments", ctx, projectID, opts)
	ret0, _ := ret[0].([]domain.TrackerProjectComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectComments indicates an expected call of ListProjectComments.
func (mr *MockITrackerAdapterMockRecorder) ListProjectComments(ctx, projectID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectComments", reflect.TypeOf((*MockITrackerAdapter)(nil).ListProjectComments), ctx, projectID, opts)
}

// ListQueues mocks base method.
func (m *MockITrackerAdapter) ListQueues(ctx context.Context, opts domain.TrackerListQueuesOpts) (*domain.TrackerQueuesPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQueues", ctx, opts)
	ret0, _ := ret[0].(*domain.TrackerQueuesPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQueues indicates an expected call of ListQueues.
func (mr *MockITrackerAdapterMockRecorder) ListQueues(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQueues", reflect.TypeOf((*MockITrackerAdapter)(nil).ListQueues), ctx, opts)
}

// ListUsers mocks base method.
func (m *MockITrackerAdapter) ListUsers(ctx context.Context, opts domain.TrackerListUsersOpts) (*domain.TrackerUsersPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, opts)
	ret0, _ := ret[0].(*domain.TrackerUsersPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockITrackerAdapterMockRecorder) ListUsers(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockITrackerAdapter)(nil).ListUsers), ctx, opts)
}

// SearchIssues mocks base method.
func (m *MockITrackerAdapter) SearchIssues(ctx context.Context, opts domain.TrackerSearchIssuesOpts) (*domain.TrackerIssuesPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchIssues", ctx, opts)
	ret0, _ := ret[0].(*domain.TrackerIssuesPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchIssues indicates an expected call of SearchIssues.
func (mr *MockITrackerAdapterMockRecorder) SearchIssues(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchIssues", reflect.TypeOf((*MockITrackerAdapter)(nil).SearchIssues), ctx, opts)
}
